[package]
name = "mockall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.11.3"
tokio = { version = "1", features = ["full"] }
time = "0.3.16"
again = "0.1.2"